In [124]:
pip install transformers

Note: you may need to restart the kernel to use updated packages.


In [125]:
import pandas as pd
import numpy as np

In [126]:
df = pd.read_csv('../interpark.csv', index_col=0)
df

review        date  \
0    이박하는 동안불편함없이 객실도깨끗하고 식기류도 깔끔해서좋습니다 황태해장국도 맛나고....  2023-11-10   
1    날씨가 흐렸지만.\n쾌적하게 잘 다녀왔어요....\n방 배정도 잘 받아서  방해받지...  2023-09-06   
2                                         오래됐지만 괜찮은 숙소  2023-09-05   
3    막  들어가자마자  오래된 냄새 빼고는 몇년전에  리모델링해서 깔끔하고  좋았어요 ...  2023-09-03   
4    설악산갈때마다이용하는리조트입니다.2년전에는부분적으로리모델링이되어있었는데이번에가보니객...  2023-07-19   
..                                                 ...         ...   
216  아무리 회원이 아니고 숙박앱 통해서 갔다해도 이건 너무하네요. 서울에서 늦게 출발해...  2020-01-11   
217  리모델링한지 2년된 룸이여서 그런지\n깨끗하고 잘 정돈되어있어서 너무 쾌적했습니다\...  2020-01-07   
218  연말 가족모임으로 이용하고 왔습니다.\n시설을 오래됐지만 청소상태는 좋았습니다.\n...  2019-12-30   
219                     좋았습니다. 가족들 모두 편안하게 숙박했고 평이좋았음.  2019-12-30   
220  물도 좋고 공기도 좋고 넓은 스위트 디럭스 방문을 여니 뽀송뽀송한 좋은 침구 냄새와...  2019-12-23   

                    rates  
0    [10, 10, 10, 10, 10]  
1    [10, 10, 10, 10, 10]  
2         [8, 8, 8, 8, 8]  
3    [10, 10, 10, 10, 10]  
4    [10, 10, 10, 10, 10]  
..                    ...  
216       [2, 2, 2, 2, 4]  
217  [10, 10, 10, 10, 10]  
218      [7, 8, 10, 8, 8]  
219       [6, 6, 6, 6, 6]  
220  [10, 10, 10, 10, 10]  

[221 rows x 3 columns]

In [127]:
import ast 
df['rates'] = df['rates'].apply(ast.literal_eval)

def change(x):
    if sum(x) == 50:
        return [5, 5, 5, 5, 5]
    else:
        return x
    
df['rates2'] = df['rates'].apply(lambda x: [5, 5, 5, 5, 5] if sum(x) == 50 else x)

In [128]:
df

review        date  \
0    이박하는 동안불편함없이 객실도깨끗하고 식기류도 깔끔해서좋습니다 황태해장국도 맛나고....  2023-11-10   
1    날씨가 흐렸지만.\n쾌적하게 잘 다녀왔어요....\n방 배정도 잘 받아서  방해받지...  2023-09-06   
2                                         오래됐지만 괜찮은 숙소  2023-09-05   
3    막  들어가자마자  오래된 냄새 빼고는 몇년전에  리모델링해서 깔끔하고  좋았어요 ...  2023-09-03   
4    설악산갈때마다이용하는리조트입니다.2년전에는부분적으로리모델링이되어있었는데이번에가보니객...  2023-07-19   
..                                                 ...         ...   
216  아무리 회원이 아니고 숙박앱 통해서 갔다해도 이건 너무하네요. 서울에서 늦게 출발해...  2020-01-11   
217  리모델링한지 2년된 룸이여서 그런지\n깨끗하고 잘 정돈되어있어서 너무 쾌적했습니다\...  2020-01-07   
218  연말 가족모임으로 이용하고 왔습니다.\n시설을 오래됐지만 청소상태는 좋았습니다.\n...  2019-12-30   
219                     좋았습니다. 가족들 모두 편안하게 숙박했고 평이좋았음.  2019-12-30   
220  물도 좋고 공기도 좋고 넓은 스위트 디럭스 방문을 여니 뽀송뽀송한 좋은 침구 냄새와...  2019-12-23   

                    rates            rates2  
0    [10, 10, 10, 10, 10]   [5, 5, 5, 5, 5]  
1    [10, 10, 10, 10, 10]   [5, 5, 5, 5, 5]  
2         [8, 8, 8, 8, 8]   [8, 8, 8, 8, 8]  
3    [10, 10, 10, 10, 10]   [5, 5, 5, 5, 5]  
4    [10, 10, 10, 10, 10]   [5, 5, 5, 5, 5]  
..                    ...               ...  
216       [2, 2, 2, 2, 4]   [2, 2, 2, 2, 4]  
217  [10, 10, 10, 10, 10]   [5, 5, 5, 5, 5]  
218      [7, 8, 10, 8, 8]  [7, 8, 10, 8, 8]  
219       [6, 6, 6, 6, 6]   [6, 6, 6, 6, 6]  
220  [10, 10, 10, 10, 10]   [5, 5, 5, 5, 5]  

[221 rows x 4 columns]

In [129]:
max_length = 30
batch_size = 64
num_epochs = 3
valid_split = 0.2

In [123]:
from transformers import BertTokenizer, BertForSequenceClassification
from transformers import AdamW
import torch
from torch.utils.data import DataLoader, TensorDataset
from tqdm import tqdm

# 데이터셋 가정 
texts = df['review'].tolist()
labels = df['rates2'].tolist()
num_labels = len(labels[0])

tokenizer = BertTokenizer.from_pretrained('monologg/kobert', do_lower_case=False)

# 토큰화 함수
def tokenize_texts(texts):
    return tokenizer(texts, padding=True, truncation=True, max_length=max_length, return_tensors="pt")

tokenized_texts = tokenize_texts(texts)
labels = torch.tensor(labels, dtype=torch.float)
dataset = TensorDataset(tokenized_texts['input_ids'], tokenized_texts['attention_mask'], tokenized_texts['token_type_ids'], labels)
dataloader = DataLoader(dataset, batch_size=batch_size, shuffle=True)

model = BertForSequenceClassification.from_pretrained('monologg/kobert', num_labels=num_labels)
optimizer = AdamW(model.parameters(), lr=5e-5)

for epoch in tqdm(range(num_epochs)):
    for batch in dataloader:
        input_ids, attention_masks, token_type_ids, labels = batch
        outputs = model(input_ids=input_ids, attention_mask=attention_masks, token_type_ids=token_type_ids, labels=labels)
        loss = outputs.loss
        loss.backward()
        optimizer.step()
        optimizer.zero_grad()


Some weights of BertForSequenceClassification were not initialized from the model checkpoint at monologg/kobert and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
100%|██████████| 3/3 [01:03<00:00, 21.05s/it]


In [ ]:
idx = 211
print(tokenized_texts['input_ids'][idx])
print(tokenized_texts['attention_mask'][idx])
print(tokenized_texts['token_type_ids'][idx])

tensor([   2,    0,    0,   54,    0,    0, 7867,    0,    0,    0,   54,    0,
           0,   54, 7266,    0,   54,    0,    0,   54,    3,    1,    1,    1,
           1,    1,    1,    1,    1,    1])
tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0])


In [131]:
env_name = ['시설(객실/부대시설)',
'위치',
'청결',
'서비스',
'분위기']

def predict_labels(test_texts):
    test_tokenized_texts = tokenizer(test_texts, padding=True, truncation=True, return_tensors="pt")
    test_outputs = model(**test_tokenized_texts)
    predicted_probs = torch.sigmoid(test_outputs.logits)

    # 결과 출력
    for i, test_text in enumerate(test_texts):
        print(f"입력값: {test_text}")
        for j, prob in enumerate(predicted_probs[i]):
            print(f"{env_name[j]} : {prob.item()*100:.2f}%")
        print("\n")

# 테스트 실행
test_texts = ["아무리 회원이 아니고 숙박앱 통해서 갔다해도 이건 너무하네요.", "경치가 좋은 곳에 가고싶어요."]
predict_labels(test_texts)

입력값: 아무리 회원이 아니고 숙박앱 통해서 갔다해도 이건 너무하네요.
시설(객실/부대시설) : 58.14%
위치 : 68.78%
청결 : 61.07%
서비스 : 49.42%
분위기 : 49.03%


입력값: 경치가 좋은 곳에 가고싶어요.
시설(객실/부대시설) : 57.81%
위치 : 68.32%
청결 : 60.51%
서비스 : 45.64%
분위기 : 49.13%




In [ ]:
predicted_probs

tensor([[0.9303, 0.9696, 0.9513, 0.9643, 0.9529],
        [0.9304, 0.9694, 0.9511, 0.9641, 0.9530]], grad_fn=<SigmoidBackward0>)